/**
 *
 * $Id$
 */
package de.familytree.familytree.validation;

import de.familytree.familytree.Person;
import de.familytree.familytree.RelationshipStatus;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.familytree.familytree.Person}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateFirstName(String value);
	boolean validateSecondName(String value);
	boolean validateChildren(EList<Person> value);
	boolean validateParents(EList<Person> value);
	boolean validateDayOfBirth(Date value);
	boolean validateNameOfBirth(String value);
	boolean validateRelationshipStatus(RelationshipStatus value);
	boolean validateDied(boolean value);
	boolean validateDayOfDeath(Date value);
	boolean validateLocationOfBirth(String value);
	boolean validateInRelationWith(Person value);
	boolean validateInRelationTo(Person value);
	boolean validateImagePaths(EList<String> value);
}
